apiVersion: extensions/v1beta1
kind: Deployment
spec:
    replicas: {{ .Values.replicaCount }}
strategy:
    rollingUpdate:
        maxSurge: 1
        maxUnavailable: 1
    type: RollingUpdate
template:
    spec:
        containers:
        - name: {{ template "nats.name" . }}
          image: {{ template "nats.image" . }}