apiVersion: v1
kind: Service
metadata:
  name: {{ template "nats.fullname" . }}
  labels: 
    app: "{{ template "nats.name" . }}"
    chart: {{template "nats.chart" . }}
    release: "{{ .Release.Name }}"
  ports: 
  - name: client
    port: 4222
    targetPort: client